version: "3.8"
services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017-27019:27017-27019"
    networks:
      - backend

  service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      - backend

networks:
  frontend:
  backend:
